//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthShoreSurfApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthShoreSurfApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpool.
        /// </summary>
        internal static string carpool {
            get {
                return ResourceManager.GetString("carpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking phone no.
        ///Please wait....
        /// </summary>
        internal static string checking_phone_no_please_wait {
            get {
                return ResourceManager.GetString("checking_phone_no_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for more info.
        /// </summary>
        internal static string click_for_more_info {
            get {
                return ResourceManager.GetString("click_for_more_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to
        ///find out how
        ///to contact us.
        /// </summary>
        internal static string click_here_to_find_out_how_to_contact_us {
            get {
                return ResourceManager.GetString("click_here_to_find_out_how_to_contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to
        ///read about all
        ///the available
        ///courses.
        /// </summary>
        internal static string click_here_to_read_about_all_the_available_courses {
            get {
                return ResourceManager.GetString("click_here_to_read_about_all_the_available_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string contact_us {
            get {
                return ResourceManager.GetString("contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add events to carpool event.
        /// </summary>
        internal static string could_not_add_events_to_carpool_event {
            get {
                return ResourceManager.GetString("could_not_add_events_to_carpool_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add events to carpool request.
        /// </summary>
        internal static string could_not_add_events_to_carpool_request {
            get {
                return ResourceManager.GetString("could_not_add_events_to_carpool_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not answer confirmation.
        /// </summary>
        internal static string could_not_answer_confirmation {
            get {
                return ResourceManager.GetString("could_not_answer_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create carpool event.
        /// </summary>
        internal static string could_not_create_carpool_event {
            get {
                return ResourceManager.GetString("could_not_create_carpool_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create carpool request.
        /// </summary>
        internal static string could_not_create_carpool_request {
            get {
                return ResourceManager.GetString("could_not_create_carpool_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete invite.
        /// </summary>
        internal static string could_not_delete_invite {
            get {
                return ResourceManager.GetString("could_not_delete_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not invite passenger.
        /// </summary>
        internal static string could_not_invite_passenger {
            get {
                return ResourceManager.GetString("could_not_invite_passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign up to carpool event.
        /// </summary>
        internal static string could_not_sign_up_to_carpool {
            get {
                return ResourceManager.GetString("could_not_sign_up_to_carpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not unsign from carpool event.
        /// </summary>
        internal static string could_not_unsign_from_carpool {
            get {
                return ResourceManager.GetString("could_not_unsign_from_carpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating account.
        ///Please wait....
        /// </summary>
        internal static string creating_account_please_wait {
            get {
                return ResourceManager.GetString("creating_account_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s).
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string every_day {
            get {
                return ResourceManager.GetString("every_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting data.
        ///Please wait....
        /// </summary>
        internal static string getting_data_please_wait {
            get {
                return ResourceManager.GetString("getting_data_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        internal static string holidays {
            get {
                return ResourceManager.GetString("holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour(s).
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Webcam.
        /// </summary>
        internal static string live_webcam {
            get {
                return ResourceManager.GetString("live_webcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute(s).
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Ride in.
        /// </summary>
        internal static string next_ride_in {
            get {
                return ResourceManager.GetString("next_ride_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next ride to Løkken in.
        /// </summary>
        internal static string next_ride_to_lokken_in {
            get {
                return ResourceManager.GetString("next_ride_to_lokken_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean conditions.
        /// </summary>
        internal static string ocean_conditions {
            get {
                return ResourceManager.GetString("ocean_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        internal static string opening_hours {
            get {
                return ResourceManager.GetString("opening_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are open school breaks all year and bookings are always available.
        ///Contact by mail is available at all times.
        ///
        ///{0}
        ///
        ///The weather is essential for operation of business which unfortunately can cause the café to close..
        /// </summary>
        internal static string opening_hours_details {
            get {
                return ResourceManager.GetString("opening_hours_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone no..
        /// </summary>
        internal static string phone_no {
            get {
                return ResourceManager.GetString("phone_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all the empty fields.
        /// </summary>
        internal static string please_fill_out_all_the_empty_fields {
            get {
                return ResourceManager.GetString("please_fill_out_all_the_empty_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} second(s).
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See webcam.
        /// </summary>
        internal static string see_webcam {
            get {
                return ResourceManager.GetString("see_webcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0}.
        /// </summary>
        internal static string select_parameter {
            get {
                return ResourceManager.GetString("select_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS code.
        /// </summary>
        internal static string sms_code {
            get {
                return ResourceManager.GetString("sms_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURF &amp; SUP.
        /// </summary>
        internal static string surf_and_sup_courses {
            get {
                return ResourceManager.GetString("surf_and_sup_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist.
        /// </summary>
        internal static string user_already_exist {
            get {
                return ResourceManager.GetString("user_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active..
        /// </summary>
        internal static string user_is_not_active {
            get {
                return ResourceManager.GetString("user_is_not_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather conditions.
        /// </summary>
        internal static string weather_conditions {
            get {
                return ResourceManager.GetString("weather_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to North Shore Surf Løkken.
        /// </summary>
        internal static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are good surfing conditions.
        /// </summary>
        internal static string what_are_good_surfing_conditions {
            get {
                return ResourceManager.GetString("what_are_good_surfing_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good surfing conditions are present when the wave and swell size are close to each other.
        ///Surfing is possible at all temperatures, but it is important to dress according to the weather..
        /// </summary>
        internal static string what_are_good_surfing_conditions_description {
            get {
                return ResourceManager.GetString("what_are_good_surfing_conditions_description", resourceCulture);
            }
        }
    }
}
