//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthShoreSurfApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NorthShoreSurfApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string carpool {
            get {
                return ResourceManager.GetString("carpool", resourceCulture);
            }
        }
        
        internal static string checking_phone_no_please_wait {
            get {
                return ResourceManager.GetString("checking_phone_no_please_wait", resourceCulture);
            }
        }
        
        internal static string click_for_more_info {
            get {
                return ResourceManager.GetString("click_for_more_info", resourceCulture);
            }
        }
        
        internal static string click_here_to_find_out_how_to_contact_us {
            get {
                return ResourceManager.GetString("click_here_to_find_out_how_to_contact_us", resourceCulture);
            }
        }
        
        internal static string click_here_to_read_about_all_the_available_courses {
            get {
                return ResourceManager.GetString("click_here_to_read_about_all_the_available_courses", resourceCulture);
            }
        }
        
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        internal static string contact_us {
            get {
                return ResourceManager.GetString("contact_us", resourceCulture);
            }
        }
        
        internal static string continue_as_guest {
            get {
                return ResourceManager.GetString("continue_as_guest", resourceCulture);
            }
        }
        
        internal static string could_not_add_events_to_carpool_event {
            get {
                return ResourceManager.GetString("could_not_add_events_to_carpool_event", resourceCulture);
            }
        }
        
        internal static string could_not_add_events_to_carpool_request {
            get {
                return ResourceManager.GetString("could_not_add_events_to_carpool_request", resourceCulture);
            }
        }
        
        internal static string could_not_answer_confirmation {
            get {
                return ResourceManager.GetString("could_not_answer_confirmation", resourceCulture);
            }
        }
        
        internal static string could_not_create_carpool_event {
            get {
                return ResourceManager.GetString("could_not_create_carpool_event", resourceCulture);
            }
        }
        
        internal static string could_not_create_carpool_request {
            get {
                return ResourceManager.GetString("could_not_create_carpool_request", resourceCulture);
            }
        }
        
        internal static string could_not_delete_invite {
            get {
                return ResourceManager.GetString("could_not_delete_invite", resourceCulture);
            }
        }
        
        internal static string could_not_invite_passenger {
            get {
                return ResourceManager.GetString("could_not_invite_passenger", resourceCulture);
            }
        }
        
        internal static string could_not_sign_up_to_carpool {
            get {
                return ResourceManager.GetString("could_not_sign_up_to_carpool", resourceCulture);
            }
        }
        
        internal static string could_not_unsign_from_carpool {
            get {
                return ResourceManager.GetString("could_not_unsign_from_carpool", resourceCulture);
            }
        }
        
        internal static string creating_account_please_wait {
            get {
                return ResourceManager.GetString("creating_account_please_wait", resourceCulture);
            }
        }
        
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        internal static string edit_information {
            get {
                return ResourceManager.GetString("edit_information", resourceCulture);
            }
        }
        
        internal static string every_day {
            get {
                return ResourceManager.GetString("every_day", resourceCulture);
            }
        }
        
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        internal static string getting_data_please_wait {
            get {
                return ResourceManager.GetString("getting_data_please_wait", resourceCulture);
            }
        }
        
        internal static string holidays {
            get {
                return ResourceManager.GetString("holidays", resourceCulture);
            }
        }
        
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        internal static string live_webcam {
            get {
                return ResourceManager.GetString("live_webcam", resourceCulture);
            }
        }
        
        internal static string log_in {
            get {
                return ResourceManager.GetString("log_in", resourceCulture);
            }
        }
        
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        internal static string next_ride_in {
            get {
                return ResourceManager.GetString("next_ride_in", resourceCulture);
            }
        }
        
        internal static string next_ride_to_lokken_in {
            get {
                return ResourceManager.GetString("next_ride_to_lokken_in", resourceCulture);
            }
        }
        
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        internal static string ocean_conditions {
            get {
                return ResourceManager.GetString("ocean_conditions", resourceCulture);
            }
        }
        
        internal static string opening_hours {
            get {
                return ResourceManager.GetString("opening_hours", resourceCulture);
            }
        }
        
        internal static string opening_hours_details {
            get {
                return ResourceManager.GetString("opening_hours_details", resourceCulture);
            }
        }
        
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        internal static string phone_no {
            get {
                return ResourceManager.GetString("phone_no", resourceCulture);
            }
        }
        
        internal static string please_enter_sms_code {
            get {
                return ResourceManager.GetString("please_enter_sms_code", resourceCulture);
            }
        }
        
        internal static string please_fill_out_all_the_empty_fields {
            get {
                return ResourceManager.GetString("please_fill_out_all_the_empty_fields", resourceCulture);
            }
        }
        
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        internal static string see_webcam {
            get {
                return ResourceManager.GetString("see_webcam", resourceCulture);
            }
        }
        
        internal static string select_parameter {
            get {
                return ResourceManager.GetString("select_parameter", resourceCulture);
            }
        }
        
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        internal static string sms_code {
            get {
                return ResourceManager.GetString("sms_code", resourceCulture);
            }
        }
        
        internal static string surf_and_sup_courses {
            get {
                return ResourceManager.GetString("surf_and_sup_courses", resourceCulture);
            }
        }
        
        internal static string this_phone_no_is_not_used_on_any_existing_accounts {
            get {
                return ResourceManager.GetString("this_phone_no_is_not_used_on_any_existing_accounts", resourceCulture);
            }
        }
        
        internal static string user_already_exist {
            get {
                return ResourceManager.GetString("user_already_exist", resourceCulture);
            }
        }
        
        internal static string user_is_not_active {
            get {
                return ResourceManager.GetString("user_is_not_active", resourceCulture);
            }
        }
        
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        internal static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        internal static string weather_conditions {
            get {
                return ResourceManager.GetString("weather_conditions", resourceCulture);
            }
        }
        
        internal static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        internal static string what_are_good_surfing_conditions {
            get {
                return ResourceManager.GetString("what_are_good_surfing_conditions", resourceCulture);
            }
        }
        
        internal static string what_are_good_surfing_conditions_description {
            get {
                return ResourceManager.GetString("what_are_good_surfing_conditions_description", resourceCulture);
            }
        }
        
        internal static string you_need_to_log_in_to_use_the_carpool_feature {
            get {
                return ResourceManager.GetString("you_need_to_log_in_to_use_the_carpool_feature", resourceCulture);
            }
        }
    }
}
